# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.3.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.3.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/markpp/Desktop/mark/trafficLightDetection

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/markpp/Desktop/mark/trafficLightDetection

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.3.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.3.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/markpp/Desktop/mark/trafficLightDetection/CMakeFiles /Users/markpp/Desktop/mark/trafficLightDetection/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/markpp/Desktop/mark/trafficLightDetection/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

src/candidateEvaluator/candidateEvaluator.o: src/candidateEvaluator/candidateEvaluator.cpp.o

.PHONY : src/candidateEvaluator/candidateEvaluator.o

# target to build an object file
src/candidateEvaluator/candidateEvaluator.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/candidateEvaluator/candidateEvaluator.cpp.o
.PHONY : src/candidateEvaluator/candidateEvaluator.cpp.o

src/candidateEvaluator/candidateEvaluator.i: src/candidateEvaluator/candidateEvaluator.cpp.i

.PHONY : src/candidateEvaluator/candidateEvaluator.i

# target to preprocess a source file
src/candidateEvaluator/candidateEvaluator.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/candidateEvaluator/candidateEvaluator.cpp.i
.PHONY : src/candidateEvaluator/candidateEvaluator.cpp.i

src/candidateEvaluator/candidateEvaluator.s: src/candidateEvaluator/candidateEvaluator.cpp.s

.PHONY : src/candidateEvaluator/candidateEvaluator.s

# target to generate assembly for a file
src/candidateEvaluator/candidateEvaluator.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/candidateEvaluator/candidateEvaluator.cpp.s
.PHONY : src/candidateEvaluator/candidateEvaluator.cpp.s

src/detectors/backproject.o: src/detectors/backproject.cpp.o

.PHONY : src/detectors/backproject.o

# target to build an object file
src/detectors/backproject.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/detectors/backproject.cpp.o
.PHONY : src/detectors/backproject.cpp.o

src/detectors/backproject.i: src/detectors/backproject.cpp.i

.PHONY : src/detectors/backproject.i

# target to preprocess a source file
src/detectors/backproject.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/detectors/backproject.cpp.i
.PHONY : src/detectors/backproject.cpp.i

src/detectors/backproject.s: src/detectors/backproject.cpp.s

.PHONY : src/detectors/backproject.s

# target to generate assembly for a file
src/detectors/backproject.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/detectors/backproject.cpp.s
.PHONY : src/detectors/backproject.cpp.s

src/detectors/blobAnalysis.o: src/detectors/blobAnalysis.cpp.o

.PHONY : src/detectors/blobAnalysis.o

# target to build an object file
src/detectors/blobAnalysis.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/detectors/blobAnalysis.cpp.o
.PHONY : src/detectors/blobAnalysis.cpp.o

src/detectors/blobAnalysis.i: src/detectors/blobAnalysis.cpp.i

.PHONY : src/detectors/blobAnalysis.i

# target to preprocess a source file
src/detectors/blobAnalysis.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/detectors/blobAnalysis.cpp.i
.PHONY : src/detectors/blobAnalysis.cpp.i

src/detectors/blobAnalysis.s: src/detectors/blobAnalysis.cpp.s

.PHONY : src/detectors/blobAnalysis.s

# target to generate assembly for a file
src/detectors/blobAnalysis.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/detectors/blobAnalysis.cpp.s
.PHONY : src/detectors/blobAnalysis.cpp.s

src/detectors/colorLight/colorLight.o: src/detectors/colorLight/colorLight.cpp.o

.PHONY : src/detectors/colorLight/colorLight.o

# target to build an object file
src/detectors/colorLight/colorLight.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/detectors/colorLight/colorLight.cpp.o
.PHONY : src/detectors/colorLight/colorLight.cpp.o

src/detectors/colorLight/colorLight.i: src/detectors/colorLight/colorLight.cpp.i

.PHONY : src/detectors/colorLight/colorLight.i

# target to preprocess a source file
src/detectors/colorLight/colorLight.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/detectors/colorLight/colorLight.cpp.i
.PHONY : src/detectors/colorLight/colorLight.cpp.i

src/detectors/colorLight/colorLight.s: src/detectors/colorLight/colorLight.cpp.s

.PHONY : src/detectors/colorLight/colorLight.s

# target to generate assembly for a file
src/detectors/colorLight/colorLight.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/detectors/colorLight/colorLight.cpp.s
.PHONY : src/detectors/colorLight/colorLight.cpp.s

src/detectors/edgeSegmentation.o: src/detectors/edgeSegmentation.cpp.o

.PHONY : src/detectors/edgeSegmentation.o

# target to build an object file
src/detectors/edgeSegmentation.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/detectors/edgeSegmentation.cpp.o
.PHONY : src/detectors/edgeSegmentation.cpp.o

src/detectors/edgeSegmentation.i: src/detectors/edgeSegmentation.cpp.i

.PHONY : src/detectors/edgeSegmentation.i

# target to preprocess a source file
src/detectors/edgeSegmentation.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/detectors/edgeSegmentation.cpp.i
.PHONY : src/detectors/edgeSegmentation.cpp.i

src/detectors/edgeSegmentation.s: src/detectors/edgeSegmentation.cpp.s

.PHONY : src/detectors/edgeSegmentation.s

# target to generate assembly for a file
src/detectors/edgeSegmentation.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/detectors/edgeSegmentation.cpp.s
.PHONY : src/detectors/edgeSegmentation.cpp.s

src/detectors/spotLight/spotLight.o: src/detectors/spotLight/spotLight.cpp.o

.PHONY : src/detectors/spotLight/spotLight.o

# target to build an object file
src/detectors/spotLight/spotLight.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/detectors/spotLight/spotLight.cpp.o
.PHONY : src/detectors/spotLight/spotLight.cpp.o

src/detectors/spotLight/spotLight.i: src/detectors/spotLight/spotLight.cpp.i

.PHONY : src/detectors/spotLight/spotLight.i

# target to preprocess a source file
src/detectors/spotLight/spotLight.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/detectors/spotLight/spotLight.cpp.i
.PHONY : src/detectors/spotLight/spotLight.cpp.i

src/detectors/spotLight/spotLight.s: src/detectors/spotLight/spotLight.cpp.s

.PHONY : src/detectors/spotLight/spotLight.s

# target to generate assembly for a file
src/detectors/spotLight/spotLight.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/detectors/spotLight/spotLight.cpp.s
.PHONY : src/detectors/spotLight/spotLight.cpp.s

src/detectors/spotLightDetection.o: src/detectors/spotLightDetection.cpp.o

.PHONY : src/detectors/spotLightDetection.o

# target to build an object file
src/detectors/spotLightDetection.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/detectors/spotLightDetection.cpp.o
.PHONY : src/detectors/spotLightDetection.cpp.o

src/detectors/spotLightDetection.i: src/detectors/spotLightDetection.cpp.i

.PHONY : src/detectors/spotLightDetection.i

# target to preprocess a source file
src/detectors/spotLightDetection.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/detectors/spotLightDetection.cpp.i
.PHONY : src/detectors/spotLightDetection.cpp.i

src/detectors/spotLightDetection.s: src/detectors/spotLightDetection.cpp.s

.PHONY : src/detectors/spotLightDetection.s

# target to generate assembly for a file
src/detectors/spotLightDetection.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/detectors/spotLightDetection.cpp.s
.PHONY : src/detectors/spotLightDetection.cpp.s

src/detectors/thresholdColor.o: src/detectors/thresholdColor.cpp.o

.PHONY : src/detectors/thresholdColor.o

# target to build an object file
src/detectors/thresholdColor.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/detectors/thresholdColor.cpp.o
.PHONY : src/detectors/thresholdColor.cpp.o

src/detectors/thresholdColor.i: src/detectors/thresholdColor.cpp.i

.PHONY : src/detectors/thresholdColor.i

# target to preprocess a source file
src/detectors/thresholdColor.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/detectors/thresholdColor.cpp.i
.PHONY : src/detectors/thresholdColor.cpp.i

src/detectors/thresholdColor.s: src/detectors/thresholdColor.cpp.s

.PHONY : src/detectors/thresholdColor.s

# target to generate assembly for a file
src/detectors/thresholdColor.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/detectors/thresholdColor.cpp.s
.PHONY : src/detectors/thresholdColor.cpp.s

src/evaluation/evaluation.o: src/evaluation/evaluation.cpp.o

.PHONY : src/evaluation/evaluation.o

# target to build an object file
src/evaluation/evaluation.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/evaluation/evaluation.cpp.o
.PHONY : src/evaluation/evaluation.cpp.o

src/evaluation/evaluation.i: src/evaluation/evaluation.cpp.i

.PHONY : src/evaluation/evaluation.i

# target to preprocess a source file
src/evaluation/evaluation.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/evaluation/evaluation.cpp.i
.PHONY : src/evaluation/evaluation.cpp.i

src/evaluation/evaluation.s: src/evaluation/evaluation.cpp.s

.PHONY : src/evaluation/evaluation.s

# target to generate assembly for a file
src/evaluation/evaluation.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/evaluation/evaluation.cpp.s
.PHONY : src/evaluation/evaluation.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/pressentation/pressentation.o: src/pressentation/pressentation.cpp.o

.PHONY : src/pressentation/pressentation.o

# target to build an object file
src/pressentation/pressentation.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/pressentation/pressentation.cpp.o
.PHONY : src/pressentation/pressentation.cpp.o

src/pressentation/pressentation.i: src/pressentation/pressentation.cpp.i

.PHONY : src/pressentation/pressentation.i

# target to preprocess a source file
src/pressentation/pressentation.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/pressentation/pressentation.cpp.i
.PHONY : src/pressentation/pressentation.cpp.i

src/pressentation/pressentation.s: src/pressentation/pressentation.cpp.s

.PHONY : src/pressentation/pressentation.s

# target to generate assembly for a file
src/pressentation/pressentation.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/pressentation/pressentation.cpp.s
.PHONY : src/pressentation/pressentation.cpp.s

src/stereo/ransac/ransac.o: src/stereo/ransac/ransac.cpp.o

.PHONY : src/stereo/ransac/ransac.o

# target to build an object file
src/stereo/ransac/ransac.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/stereo/ransac/ransac.cpp.o
.PHONY : src/stereo/ransac/ransac.cpp.o

src/stereo/ransac/ransac.i: src/stereo/ransac/ransac.cpp.i

.PHONY : src/stereo/ransac/ransac.i

# target to preprocess a source file
src/stereo/ransac/ransac.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/stereo/ransac/ransac.cpp.i
.PHONY : src/stereo/ransac/ransac.cpp.i

src/stereo/ransac/ransac.s: src/stereo/ransac/ransac.cpp.s

.PHONY : src/stereo/ransac/ransac.s

# target to generate assembly for a file
src/stereo/ransac/ransac.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/stereo/ransac/ransac.cpp.s
.PHONY : src/stereo/ransac/ransac.cpp.s

src/tracking/kalmanfilter2d.o: src/tracking/kalmanfilter2d.cpp.o

.PHONY : src/tracking/kalmanfilter2d.o

# target to build an object file
src/tracking/kalmanfilter2d.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/tracking/kalmanfilter2d.cpp.o
.PHONY : src/tracking/kalmanfilter2d.cpp.o

src/tracking/kalmanfilter2d.i: src/tracking/kalmanfilter2d.cpp.i

.PHONY : src/tracking/kalmanfilter2d.i

# target to preprocess a source file
src/tracking/kalmanfilter2d.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/tracking/kalmanfilter2d.cpp.i
.PHONY : src/tracking/kalmanfilter2d.cpp.i

src/tracking/kalmanfilter2d.s: src/tracking/kalmanfilter2d.cpp.s

.PHONY : src/tracking/kalmanfilter2d.s

# target to generate assembly for a file
src/tracking/kalmanfilter2d.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/tracking/kalmanfilter2d.cpp.s
.PHONY : src/tracking/kalmanfilter2d.cpp.s

src/trafficSignal/trafficSignal.o: src/trafficSignal/trafficSignal.cpp.o

.PHONY : src/trafficSignal/trafficSignal.o

# target to build an object file
src/trafficSignal/trafficSignal.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/trafficSignal/trafficSignal.cpp.o
.PHONY : src/trafficSignal/trafficSignal.cpp.o

src/trafficSignal/trafficSignal.i: src/trafficSignal/trafficSignal.cpp.i

.PHONY : src/trafficSignal/trafficSignal.i

# target to preprocess a source file
src/trafficSignal/trafficSignal.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/trafficSignal/trafficSignal.cpp.i
.PHONY : src/trafficSignal/trafficSignal.cpp.i

src/trafficSignal/trafficSignal.s: src/trafficSignal/trafficSignal.cpp.s

.PHONY : src/trafficSignal/trafficSignal.s

# target to generate assembly for a file
src/trafficSignal/trafficSignal.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/trafficSignal/trafficSignal.cpp.s
.PHONY : src/trafficSignal/trafficSignal.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... src/candidateEvaluator/candidateEvaluator.o"
	@echo "... src/candidateEvaluator/candidateEvaluator.i"
	@echo "... src/candidateEvaluator/candidateEvaluator.s"
	@echo "... src/detectors/backproject.o"
	@echo "... src/detectors/backproject.i"
	@echo "... src/detectors/backproject.s"
	@echo "... src/detectors/blobAnalysis.o"
	@echo "... src/detectors/blobAnalysis.i"
	@echo "... src/detectors/blobAnalysis.s"
	@echo "... src/detectors/colorLight/colorLight.o"
	@echo "... src/detectors/colorLight/colorLight.i"
	@echo "... src/detectors/colorLight/colorLight.s"
	@echo "... src/detectors/edgeSegmentation.o"
	@echo "... src/detectors/edgeSegmentation.i"
	@echo "... src/detectors/edgeSegmentation.s"
	@echo "... src/detectors/spotLight/spotLight.o"
	@echo "... src/detectors/spotLight/spotLight.i"
	@echo "... src/detectors/spotLight/spotLight.s"
	@echo "... src/detectors/spotLightDetection.o"
	@echo "... src/detectors/spotLightDetection.i"
	@echo "... src/detectors/spotLightDetection.s"
	@echo "... src/detectors/thresholdColor.o"
	@echo "... src/detectors/thresholdColor.i"
	@echo "... src/detectors/thresholdColor.s"
	@echo "... src/evaluation/evaluation.o"
	@echo "... src/evaluation/evaluation.i"
	@echo "... src/evaluation/evaluation.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/pressentation/pressentation.o"
	@echo "... src/pressentation/pressentation.i"
	@echo "... src/pressentation/pressentation.s"
	@echo "... src/stereo/ransac/ransac.o"
	@echo "... src/stereo/ransac/ransac.i"
	@echo "... src/stereo/ransac/ransac.s"
	@echo "... src/tracking/kalmanfilter2d.o"
	@echo "... src/tracking/kalmanfilter2d.i"
	@echo "... src/tracking/kalmanfilter2d.s"
	@echo "... src/trafficSignal/trafficSignal.o"
	@echo "... src/trafficSignal/trafficSignal.i"
	@echo "... src/trafficSignal/trafficSignal.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

